### ISSUE TITLE
Mino-T Left-side Error

### ISSUE THREAD

**Issue by KKKKK-55555** [KKKKK-55555/Javaris#16]
# Mino T Left-side Error

Iミノを左に移動させると、壁の2つ右にあってまだ移動できそうなのに動けなくなる。

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 20
        at Javaris.GameArea.isCollison(GameArea.java:185)
        at Javaris.App$3.actionPerformed(App.java:129)

以上のエラーコードが出る。
直近のエラーはArrayIndexOutOfBoundsExceptionである。
さらに読み進めると、配列の大きさは20なのに-1やで！！とのこと。
そして大きさ20の配列はフィールドである！

**Comment by KKKKK-55555** [comment]
## 原因

- App.java, initControls()
  - 回転時のisCollisonに代入するミノ座標において、xが+1されている
  - その結果、右に移動した前提で衝突判定してしまう
  - 実際には回転時に右へ移動することはないため、エラーが起きる

## 解決法

- 今回はisCollision()で代入するx座標を+1する記述を消去し、現在のミノの座標から回転時の衝突判定をするよう変更した
